/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.fastbuy.view;

import  ec.edu.espe.fastbuy.controler.formshandler;


/**
 *
 * @author TEAM 6
 */
public class frmFastBuy extends javax.swing.JFrame {

    /**
     * Creates new form frmabout
     */
    public frmFastBuy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jButtonCarrito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mbrFastBuy = new javax.swing.JMenuBar();
        mnuFastBuy = new javax.swing.JMenu();
        itmabout = new javax.swing.JMenuItem();
        itmhelp = new javax.swing.JMenuItem();
        itmexit = new javax.swing.JMenuItem();
        mnuiniciarsesión = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnubuscar = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnunotificaciones = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carrito.png"))); // NOI18N
        jButtonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 80, 80));

        jLabel1.setText("ESCANEANDO...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 100, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Prod2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 581));

        mnuFastBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        mnuFastBuy.setText("   ");

        itmabout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itmabout.setText("Sobre la aplicación");
        itmabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmaboutActionPerformed(evt);
            }
        });
        mnuFastBuy.add(itmabout);

        itmhelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        itmhelp.setText("Ayuda");
        itmhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmhelpActionPerformed(evt);
            }
        });
        mnuFastBuy.add(itmhelp);

        itmexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itmexit.setText("Salir de la aplicación");
        itmexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmexitActionPerformed(evt);
            }
        });
        mnuFastBuy.add(itmexit);

        mbrFastBuy.add(mnuFastBuy);

        mnuiniciarsesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/person.png"))); // NOI18N
        mnuiniciarsesión.setText("    ");

        jMenuItem3.setText("Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuiniciarsesión.add(jMenuItem3);

        mbrFastBuy.add(mnuiniciarsesión);

        mnubuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        mnubuscar.setText("   ");

        jMenuItem2.setText("Buscar producto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnubuscar.add(jMenuItem2);

        mbrFastBuy.add(mnubuscar);

        mnunotificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/not.png"))); // NOI18N

        jMenuItem1.setText("Notificaciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnunotificaciones.add(jMenuItem1);

        mbrFastBuy.add(mnunotificaciones);

        setJMenuBar(mbrFastBuy);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmaboutActionPerformed
        frmAbout frmAbout = new frmAbout();
        this.setVisible(false);
        frmAbout.setVisible(true);

    }//GEN-LAST:event_itmaboutActionPerformed

    private void itmhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmhelpActionPerformed
        frmHelp frmHelp = new frmHelp();
        this.setVisible (false);
        frmHelp.setVisible(true);
    }//GEN-LAST:event_itmhelpActionPerformed

    private void itmexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmexitActionPerformed
        
    }//GEN-LAST:event_itmexitActionPerformed

    private void jButtonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarritoActionPerformed
        frmCarrito frmCarrito = new frmCarrito();
        this.setVisible (false);
        frmCarrito.setVisible(true);
    }//GEN-LAST:event_jButtonCarritoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmNotificaciones frmNotificaciones = new frmNotificaciones();
        this.setVisible (false);
        frmNotificaciones.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmBuscar frmBuscar = new frmBuscar();
        this.setVisible (false);
        frmBuscar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmUsuario frmUsuario = new frmUsuario();
        this.setVisible (false);
        frmUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFastBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFastBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFastBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFastBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFastBuy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmabout;
    private javax.swing.JMenuItem itmexit;
    private javax.swing.JMenuItem itmhelp;
    private javax.swing.JButton jButtonCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar mbrFastBuy;
    private javax.swing.JMenu mnuFastBuy;
    private javax.swing.JMenu mnubuscar;
    private javax.swing.JMenu mnuiniciarsesión;
    private javax.swing.JMenu mnunotificaciones;
    // End of variables declaration//GEN-END:variables
}
